name: jd_price

on:
    push:
      branches:
        - main
    schedule:
        - cron: '30 22 * * *' # 该时间为UTC时间，比北京时间晚8个小时，每天早上6点半自动执行

    workflow_dispatch:

jobs:
    fetch-top-posts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: npm install --only=prod
              working-directory: .
            - name: fetch
              run: node index.js
              working-directory: .
              # for github app auth
              env:
                  getCookie: ${{ secrets.getCookie }}
                  token: ${{ secrets.token }}
                  topic: ${{ secrets.topic }}
